### ISSUE TITLE
Block should save some fields to meta

### ISSUE THREAD

**Issue by arrested-developer** [arrested-developer/wordpress-event-plugin#3]
The following should be saved as meta fields.

Some will be important to sort and query events (e.g. date/time) and others will be useful to programmatically render parts of the content, rather than the full post.

- [x] URL of flyer image
- [x] Alt text to describe the flyer image (expecting images with a lot of text, so it's important to consider a11y)
- [x] date and time of event
- [x] if the event is a general meeting or not
- [x] URL of full flyer  / agenda

**Comment by arrested-developer** [comment]
Date/time should save in UTC format so it can be easily sorted / queried
e.g.

yyyy-mm-dd hh:mm:ss
